properties:
  iteration_limit: 500
  time_limit: 3600
  max_transforms: 10
  post_processing:
      all_routes: True
policy:
  files:
    uspto:
      - ../data/uspto_rxn_n5_keras_model.hdf5
      - ../data/uspto_rxn_n5_unique_templates.hdf5
stock:
  files:
    stock: aizynth_n5_stock.txt
